// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ4N7nI-53xo2AwfkprvhD4uBkh7Ah7Dc',
    appId: '1:851452201382:web:e748766292ff7f78402767',
    messagingSenderId: '851452201382',
    projectId: 'voucho-app',
    authDomain: 'voucho-app.firebaseapp.com',
    storageBucket: 'voucho-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxRdn980_d52G4dxO3c26N08AQjwXGVuk',
    appId: '1:851452201382:android:3c24f7bf2d1d37ae402767',
    messagingSenderId: '851452201382',
    projectId: 'voucho-app',
    storageBucket: 'voucho-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ_fiaChvUSybYoa9qpxIPRBw72NDuun4',
    appId: '1:851452201382:ios:47cc3941524db038402767',
    messagingSenderId: '851452201382',
    projectId: 'voucho-app',
    storageBucket: 'voucho-app.firebasestorage.app',
    iosBundleId: 'com.example.vouchoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ_fiaChvUSybYoa9qpxIPRBw72NDuun4',
    appId: '1:851452201382:ios:47cc3941524db038402767',
    messagingSenderId: '851452201382',
    projectId: 'voucho-app',
    storageBucket: 'voucho-app.firebasestorage.app',
    iosBundleId: 'com.example.vouchoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ4N7nI-53xo2AwfkprvhD4uBkh7Ah7Dc',
    appId: '1:851452201382:web:4fcba9746e4ce1a0402767',
    messagingSenderId: '851452201382',
    projectId: 'voucho-app',
    authDomain: 'voucho-app.firebaseapp.com',
    storageBucket: 'voucho-app.firebasestorage.app',
  );
}
